# Generated by Django 3.2 on 2021-12-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphentries',
            name='entry_path',
            field=models.CharField(default='', max_length=500),
        ),
    ]
