# Generated by Django 3.2 on 2021-12-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_graphentries_entry_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueentries',
            name='entry_path',
            field=models.CharField(default='', max_length=500),
        ),
    ]
