# Generated by Django 3.2 on 2022-01-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_alter_catalogueentries_entry_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphentries',
            name='entry_id',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='graphentries',
            name='entry_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='graphentries',
            name='entry_version',
            field=models.CharField(default='', max_length=500),
        ),
    ]
